// <auto-generated />

using System;
using HotelManagementSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Web.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251129231120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("HotelManagementSystem.Web.Models.AuditLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Acao")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataHora")
                    .HasColumnType("TEXT");

                b.Property<string>("Detalhes")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Tabela")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("UsuarioNome")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.ConsumoReserva", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataConsumo")
                    .HasColumnType("TEXT");

                b.Property<int>("ProdutoId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Quantidade")
                    .HasColumnType("INTEGER");

                b.Property<int>("ReservaId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("ValorUnitarioNoMomento")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("ProdutoId");

                b.HasIndex("ReservaId");

                b.ToTable("Consumos");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Familiar", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("HospedeId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Idade")
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Parentesco")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("HospedeId");

                b.ToTable("Familiares");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Hospede", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CPF")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Contato")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Endereco")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("ReservaId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ReservaId");

                b.ToTable("Hospedes");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.HotelConfiguration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CNPJ")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Contato")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Endereco")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LoginTitle")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LogoUrl")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("NomeHotel")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("NomeSistema")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Configuracoes");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Limpeza", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataLimpeza")
                    .HasColumnType("TEXT");

                b.Property<string>("Observacoes")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("QuartoId")
                    .HasColumnType("INTEGER");

                b.Property<string>("RealizadoPor")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("ReservaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("QuartoId");

                b.HasIndex("ReservaId");

                b.ToTable("Limpezas");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Produto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Produtos");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Quarto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Detalhes")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("EstaLimpo")
                    .HasColumnType("boolean");

                b.Property<bool>("EstaOcupado")
                    .HasColumnType("boolean");

                b.Property<string>("Numero")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("PrecoBase")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Quartos");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Detalhes = "Quarto simples com cama de solteiro",
                        EstaLimpo = true,
                        EstaOcupado = false,
                        Numero = "101",
                        PrecoBase = 100.00m,
                        Tipo = "Simples"
                    });
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Reserva", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Cancelada")
                    .HasColumnType("boolean");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataCheckIn")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataCheckOut")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataEntrada")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataRealCheckIn")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataSaida")
                    .HasColumnType("TEXT");

                b.Property<string>("FormaPagamento")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("HospedeId")
                    .HasColumnType("INTEGER");

                b.Property<string>("JustificativaCancelamento")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("QuantidadePessoas")
                    .HasColumnType("INTEGER");

                b.Property<int>("QuartoId")
                    .HasColumnType("INTEGER");

                b.Property<string>("UsuarioCancelamentoId")
                    .HasColumnType("TEXT");

                b.Property<string>("UsuarioCriacaoId")
                    .HasColumnType("TEXT");

                b.Property<decimal>("ValorDiariaNoMomento")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("HospedeId");

                b.HasIndex("QuartoId");

                b.ToTable("Reservas");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Role")
                    .HasColumnType("INTEGER");

                b.Property<string>("SenhaHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Usuarios");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Email = "admin@admin",
                        Nome = "Administrador",
                        Role = 0,
                        SenhaHash =
                            "AQAAAAIAAYagAAAAEDWbhmADD0LL4a/BaHuU0EHz6EnQnuJH0vKv0J0RjkhBpbeEQ2ZDtxJO3OB3WRaY/w=="
                    });
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.ConsumoReserva", b =>
            {
                b.HasOne("HotelManagementSystem.Web.Models.Produto", "Produto")
                    .WithMany()
                    .HasForeignKey("ProdutoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HotelManagementSystem.Web.Models.Reserva", "Reserva")
                    .WithMany("Consumos")
                    .HasForeignKey("ReservaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Produto");

                b.Navigation("Reserva");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Familiar", b =>
            {
                b.HasOne("HotelManagementSystem.Web.Models.Hospede", "Hospede")
                    .WithMany("Familiares")
                    .HasForeignKey("HospedeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Hospede");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Hospede", b =>
            {
                b.HasOne("HotelManagementSystem.Web.Models.Reserva", null)
                    .WithMany("HospedesSecundarios")
                    .HasForeignKey("ReservaId");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Limpeza", b =>
            {
                b.HasOne("HotelManagementSystem.Web.Models.Quarto", "Quarto")
                    .WithMany()
                    .HasForeignKey("QuartoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HotelManagementSystem.Web.Models.Reserva", "Reserva")
                    .WithMany("Limpezas")
                    .HasForeignKey("ReservaId");

                b.Navigation("Quarto");

                b.Navigation("Reserva");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Reserva", b =>
            {
                b.HasOne("HotelManagementSystem.Web.Models.Hospede", "Hospede")
                    .WithMany()
                    .HasForeignKey("HospedeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HotelManagementSystem.Web.Models.Quarto", "Quarto")
                    .WithMany()
                    .HasForeignKey("QuartoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Hospede");

                b.Navigation("Quarto");
            });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Hospede", b => { b.Navigation("Familiares"); });

            modelBuilder.Entity("HotelManagementSystem.Web.Models.Reserva", b =>
            {
                b.Navigation("Consumos");

                b.Navigation("HospedesSecundarios");

                b.Navigation("Limpezas");
            });
#pragma warning restore 612, 618
        }
    }
}
